yhino/pipenv-poetry-migrate

- pipenv_poetry_migrate/migrate.py
- tests/toml/Pipfile
- tests/toml/expect_pyproject.toml
> fixed #2 support the 'package-name[extras] = "*"' format

- .github/workflows/release.yml
- pyproject.toml
- #8 Support the git dependencies format
> Release 0.1.3

- poetry.lock
- pyproject.toml
Changed tomlkit dependency version from `>=0.5.11,<0.6.0` to `>=0.5.11,<1.0.0`.
> changed the dependent version of tomlkit

- pyproject.toml
- tests/test_pipenv_poetry_migrate.py
* tomlkit dependency version from `>=0.5.11,<0.6.0` to `>=0.5.11,<1.0.0`
> :bookmark: release 0.1.4

- .github/workflows/release.yml
- CHANGELOG.md
- poetry.lock
- pyproject.toml
Automating the release process.
> :construction_worker: automating the release process

- pyproject.toml
In some cases, the settings were overwritten unintentionally.
Delete items that have been done by default settings.
> :wrench: remove default settings for black

- .flake8
fix flake8 settings:
- `ignore` -> `extend-ignore`
- `exclude` -> `extend-exclude`
> :wrench: fix flake8 settings

- README.md
> :pencil:  clean up README and add about new options

- .github/workflows/build.yml
- .github/workflows/release.yml
The installation instructions for poetry was updated. So the installation instructions in CI were also updated.
https://github.com/python-poetry/poetry#installation
> :construction_worker:  update the poetry installer

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/snyk.yml
- README.md
- pyproject.toml
- tests/toml/Pipfile
- tests/toml/expect_pyproject.toml
- tests/toml/expect_pyproject_with_use_group_notation.toml
ref. https://github.com/github/renaming/blob/main/README.md
> :art:  change default branch to main

- pipenv_poetry_migrate/migrate.py
- tests/conftest.py
- tests/test_migrate.py
- tests/toml/poetry12_pyproject.toml
> :bug:  add exist check for `tool.poetry.dev-dependencies`

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/snyk.yml
- .github/workflows/test.yml
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Updated actions.
> :construction_worker: upgrade version of the actions

- README.md
Updated the example in README to group notation.
> :pencil: update the example to group notation

- pipenv_poetry_migrate/translator.py
- tests/toml/expect_pyproject.toml
- tests/toml/expect_pyproject_with_use_group_notation.toml
#48
----
Wrong PyPI attributes fixed. Fixed from `index` to `source`.
refs.
- https://python-poetry.org/docs/repositories/#python-package-index-pypi
> :bug: fix PyPI attribute

- poetry.lock
- pyproject.toml
> :heavy_plus_sign: add linter `tryceratops`

- poetry.lock
- pyproject.toml
> Upgrade deps

- pipenv_poetry_migrate/migrate.py
- pipenv_poetry_migrate/translator.py
- poetry.lock
- pyproject.toml
> Upgrade packages and fix linter warnings

- .gitignore
> :see_no_evil: add .tool-versions to .gitignore file

- .github/dependabot.yml
> :construction_worker: add dependabot.yml

- .github/dependabot.yml
> :construction_worker: configuration of grouped version upgrades by dependabot

- .github/dependabot.yml
> :wrench: change dependabot schedule interval to weekly

- README.md
> :pencil: fix dead link of badge

- .github/workflows/release.yml
- .github/workflows/test.yml
Fix incomplete release workflow, and other minor issues also fixed.
> :bug: fix incomplete release workflow

- poetry.lock
> :arrow_up: upgrade dependencies

- .github/dependabot.yml
Change update interval of github action dependabot to weekly.
> change the update interval of the github action dependabot

- pipenv_poetry_migrate/cli.py
Typer notation changed to use Annotated.
> :recycle: change typer notation

- poetry.lock
- pyproject.toml
> :arrow_up: upgrade deps @20240901

- .github/workflows/test.yml
> :bug: fix warning from codecov
